export const prompts: string[] = [
    "Suggest a good movie to watch.",
    "What are the top-rated shows right now?",
    "Find me something funny to watch.",
    "Any recommendations for action-packed movies?",
    "Show me romantic movies.",
    "I feel like watching something lighthearted and fun.",
    "I'm in the mood for a thriller that keeps me on edge.",
    "Give me a feel-good movie for a rainy day.",
    "Suggest a tearjerker; I want a good cry.",
    "I need an inspiring story to watch.",
    "Any good science fiction movies with time travel?",
    "Find me a mystery show with unexpected twists.",
    "Looking for historical dramas.",
    "Recommend animated movies suitable for adults.",
    "Can you show me horror movies with a psychological twist?",
    "What are some critically acclaimed foreign-language films?",
    "Suggest a show similar to 'Breaking Bad'.",
    "Find movies directed by Christopher Nolan.",
    "I want a movie with strong female leads.",
    "Show me movies about space exploration with high ratings.",
    "Comedy",
    "Thriller",
    "Drama",
    "Action",
    "Romance",
    "Sci-fi",
    "Horror",
    "Documentary",
    "Family-friendly"
];

export const quotes: string[] = [
    "Mining the offline AI vault for hidden gems...",
    "Teaching the AI new tricks with old data...",
    "Making the offline LLM do its magic...",
    "Dusting off the AI archives...",
    "Unleashing the offline neural wizardry...",
    "Feeding data into the AI hamster wheel...",
    "Cranking the gears of the local AI engine...",
    "Digging through the treasure chest of data...",
    "Polishing old algorithms for new insights...",
    "Revisiting the AI's offline brain for brilliance...",
    "Uncovering hidden gems from the offline AI vault...",
    "Whispering sweet nothings to the neural net...",
    "Unlocking the mysteries of offline intelligence...",
];

export const secondStageMessages: string[] = [
    "Exploring the vast AI cosmos for online treasures...",
    "Tuning into the infinite wisdom of the web...",
    "Sifting through digital galaxies for recommendations...",
    "Hunting for gold in the AI cloud...",
    "Surfing the web with neural precision...",
    "Letting the AI network do its thing...",
    "Cross-referencing data from the web multiverse...",
    "Casting a wide AI net in the online ocean...",
    "Scanning the digital horizons for gems...",
    "Traversing the online data jungle...",
    "Connecting to the intergalactic AI library...",
    "Synchronizing with the neural cloud...",
    "Venturing into the vast expanse of online knowledge...",
];